/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SafetySpecsRouteImport } from './routes/safety-specs'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MarketplaceListingRouteImport } from './routes/marketplace-listing'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as AppraisalsIndexRouteImport } from './routes/appraisals/index'
import { Route as InventoryVehicleIdRouteImport } from './routes/inventory/$vehicleId'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as AppraisalsNewRouteImport } from './routes/appraisals/new'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetySpecsRoute = SafetySpecsRouteImport.update({
  id: '/safety-specs',
  path: '/safety-specs',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceListingRoute = MarketplaceListingRouteImport.update({
  id: '/marketplace-listing',
  path: '/marketplace-listing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppraisalsIndexRoute = AppraisalsIndexRouteImport.update({
  id: '/appraisals/',
  path: '/appraisals/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryVehicleIdRoute = InventoryVehicleIdRouteImport.update({
  id: '/inventory/$vehicleId',
  path: '/inventory/$vehicleId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AppraisalsNewRoute = AppraisalsNewRouteImport.update({
  id: '/appraisals/new',
  path: '/appraisals/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/leads': typeof LeadsRoute
  '/marketplace': typeof MarketplaceRoute
  '/marketplace-listing': typeof MarketplaceListingRoute
  '/pricing': typeof PricingRoute
  '/reports': typeof ReportsRoute
  '/safety-specs': typeof SafetySpecsRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/appraisals/new': typeof AppraisalsNewRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/inventory/$vehicleId': typeof InventoryVehicleIdRoute
  '/appraisals': typeof AppraisalsIndexRoute
  '/inventory': typeof InventoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/leads': typeof LeadsRoute
  '/marketplace': typeof MarketplaceRoute
  '/marketplace-listing': typeof MarketplaceListingRoute
  '/pricing': typeof PricingRoute
  '/reports': typeof ReportsRoute
  '/safety-specs': typeof SafetySpecsRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/appraisals/new': typeof AppraisalsNewRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/inventory/$vehicleId': typeof InventoryVehicleIdRoute
  '/appraisals': typeof AppraisalsIndexRoute
  '/inventory': typeof InventoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/leads': typeof LeadsRoute
  '/marketplace': typeof MarketplaceRoute
  '/marketplace-listing': typeof MarketplaceListingRoute
  '/pricing': typeof PricingRoute
  '/reports': typeof ReportsRoute
  '/safety-specs': typeof SafetySpecsRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/appraisals/new': typeof AppraisalsNewRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/inventory/$vehicleId': typeof InventoryVehicleIdRoute
  '/appraisals/': typeof AppraisalsIndexRoute
  '/inventory/': typeof InventoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/leads'
    | '/marketplace'
    | '/marketplace-listing'
    | '/pricing'
    | '/reports'
    | '/safety-specs'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/appraisals/new'
    | '/checkout/success'
    | '/inventory/$vehicleId'
    | '/appraisals'
    | '/inventory'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/leads'
    | '/marketplace'
    | '/marketplace-listing'
    | '/pricing'
    | '/reports'
    | '/safety-specs'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/appraisals/new'
    | '/checkout/success'
    | '/inventory/$vehicleId'
    | '/appraisals'
    | '/inventory'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/leads'
    | '/marketplace'
    | '/marketplace-listing'
    | '/pricing'
    | '/reports'
    | '/safety-specs'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/appraisals/new'
    | '/checkout/success'
    | '/inventory/$vehicleId'
    | '/appraisals/'
    | '/inventory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LeadsRoute: typeof LeadsRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MarketplaceListingRoute: typeof MarketplaceListingRoute
  PricingRoute: typeof PricingRoute
  ReportsRoute: typeof ReportsRoute
  SafetySpecsRoute: typeof SafetySpecsRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  AppraisalsNewRoute: typeof AppraisalsNewRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  InventoryVehicleIdRoute: typeof InventoryVehicleIdRoute
  AppraisalsIndexRoute: typeof AppraisalsIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety-specs': {
      id: '/safety-specs'
      path: '/safety-specs'
      fullPath: '/safety-specs'
      preLoaderRoute: typeof SafetySpecsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace-listing': {
      id: '/marketplace-listing'
      path: '/marketplace-listing'
      fullPath: '/marketplace-listing'
      preLoaderRoute: typeof MarketplaceListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appraisals/': {
      id: '/appraisals/'
      path: '/appraisals'
      fullPath: '/appraisals'
      preLoaderRoute: typeof AppraisalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/$vehicleId': {
      id: '/inventory/$vehicleId'
      path: '/inventory/$vehicleId'
      fullPath: '/inventory/$vehicleId'
      preLoaderRoute: typeof InventoryVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appraisals/new': {
      id: '/appraisals/new'
      path: '/appraisals/new'
      fullPath: '/appraisals/new'
      preLoaderRoute: typeof AppraisalsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LeadsRoute: LeadsRoute,
  MarketplaceRoute: MarketplaceRoute,
  MarketplaceListingRoute: MarketplaceListingRoute,
  PricingRoute: PricingRoute,
  ReportsRoute: ReportsRoute,
  SafetySpecsRoute: SafetySpecsRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  AppraisalsNewRoute: AppraisalsNewRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  InventoryVehicleIdRoute: InventoryVehicleIdRoute,
  AppraisalsIndexRoute: AppraisalsIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
